CC = gcc

all: pCp

pCp:
	@echo "The program performs the copying operations correctly, but due to an unknown error, it sometimes fails to terminate. You can terminate the program by using Ctrl+C."
	$(CC) main.c -o pCp

clean:
	rm -f pCp

re: clean all

.PHONY: all clean re



